# Generated by Django 5.2.12 on 2026-04-05 17:33

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_patient_emergency_contact'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MoodEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mood', models.CharField(choices=[('stable', 'Stable'), ('happy', 'Happy/Engaged'), ('anxious', 'Anxious'), ('confused', 'Confused'), ('agitated', 'Agitated'), ('withdrawn', 'Withdrawn'), ('sad', 'Sad')], max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('logged_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('caregiver', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mood_entries', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mood_entries', to='dashboard.patient')),
            ],
            options={
                'ordering': ['-logged_at'],
            },
        ),
        migrations.CreateModel(
            name='PhysicalConditionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blood_pressure_systolic', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('blood_pressure_diastolic', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('heart_rate', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('temperature_celsius', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('oxygen_saturation', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('appetite', models.CharField(blank=True, choices=[('good', 'Good'), ('fair', 'Fair'), ('poor', 'Poor'), ('none', 'No Appetite')], max_length=10)),
                ('sleep', models.CharField(blank=True, choices=[('full', 'Full Night (7h+)'), ('partial', 'Partial (4–6h)'), ('poor', 'Poor (under 4h)'), ('disturbed', 'Disturbed/Restless')], max_length=10)),
                ('pain_level', models.CharField(choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10')], default='0', max_length=2)),
                ('mobility_ok', models.BooleanField(default=True)),
                ('fall_risk', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('logged_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('caregiver', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='physical_logs', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='physical_logs', to='dashboard.patient')),
            ],
            options={
                'ordering': ['-logged_at'],
            },
        ),
    ]
