# Generated by Django 5.2.12 on 2026-04-06 13:13

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_moodentry_physicalconditionlog'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200)),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('dominant_mood', models.CharField(blank=True, choices=[('calm', 'Calm'), ('happy', 'Happy'), ('anxious', 'Anxious'), ('distressed', 'Distressed'), ('confused', 'Confused'), ('neutral', 'Neutral')], max_length=20)),
                ('flags', models.TextField(blank=True)),
                ('message_count', models.PositiveIntegerField(default=0)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_sessions', to='dashboard.patient')),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.CharField(choices=[('bot', 'CareBot'), ('patient', 'Patient'), ('system', 'System')], max_length=10)),
                ('content', models.TextField()),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('detected_mood', models.CharField(blank=True, choices=[('calm', 'Calm'), ('happy', 'Happy'), ('anxious', 'Anxious'), ('distressed', 'Distressed'), ('confused', 'Confused'), ('neutral', 'Neutral')], max_length=20)),
                ('flagged_keywords', models.JSONField(blank=True, default=list)),
                ('audio_file', models.FileField(blank=True, null=True, upload_to='chat_audio/')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='dashboard.chatsession')),
            ],
            options={
                'ordering': ['timestamp'],
            },
        ),
    ]
